# Generated by Django 5.0.14 on 2026-06-12 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_organizationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('educacao', 'Educação'), ('saude', 'Saúde'), ('tecnologia', 'Tecnologia'), ('meio_ambiente', 'Meio Ambiente'), ('assistencia_social', 'Assistência Social'), ('arte_cultura', 'Arte & Cultura'), ('esporte', 'Esporte')], max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('workload_value', models.PositiveIntegerField()),
                ('workload_unit', models.CharField(max_length=50)),
                ('vacancies', models.PositiveIntegerField()),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(default=list)),
                ('accepts_any_course', models.BooleanField(default=True)),
                ('preferred_courses', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('paused', 'Pausada'), ('closed', 'Encerrada')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='users.organizationprofile')),
            ],
            options={
                'db_table': 'opportunities_opportunity',
            },
        ),
        migrations.CreateModel(
            name='OpportunityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='opportunities/photos/')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='opportunities.opportunity')),
            ],
            options={
                'db_table': 'opportunities_opportunityphoto',
            },
        ),
    ]
