# Generated by Django 5.2.15 on 2026-06-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='area',
            field=models.CharField(blank=True, choices=[('educacao', 'Educação'), ('saude', 'Saúde'), ('tecnologia', 'Tecnologia'), ('meio_ambiente', 'Meio Ambiente'), ('assistencia_social', 'Assistência Social'), ('arte_cultura', 'Arte & Cultura'), ('esporte', 'Esporte')], max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
