# Generated by Django 5.2.15 on 2026-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="hours_completed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Aguardando avaliação"),
                    ("approved", "Aprovada"),
                    ("rejected", "Rejeitada"),
                    ("cancelled", "Cancelada"),
                    ("completed", "Concluída"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
