# Generated by Django 5.2.15 on 2026-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_completed_at_application_hours_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attendance',
            field=models.CharField(blank=True, choices=[('present', 'Presente'), ('partial', 'Parcial'), ('absent', 'Ausente')], max_length=10, null=True),
        ),
    ]
