# Generated by Django 5.0.14 on 2026-05-24 00:31

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[users.models.validar_cnpj]),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (xx) x xxxx-xxxx.', regex='^\\(\\d{2}\\) \\d \\d{4}-\\d{4}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('organizacao', 'Organizacao'), ('admin', 'Admin')], default='estudante', max_length=20),
        ),
    ]
