# Generated by Django 5.0.14 on 2026-06-08 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_avatar_banner_bio_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='areas_de_atuacao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='org_banners/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='endereco',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='full_description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='mission',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='site',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OrgGalleryPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='org_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='users.organizationprofile')),
            ],
            options={
                'verbose_name': 'Foto da Galeria (Org)',
                'verbose_name_plural': 'Fotos da Galeria (Org)',
                'db_table': 'users_orggalleryphoto',
                'ordering': ['-created_at'],
            },
        ),
    ]
